spring:
  application:
     name: client-service
logging:  
  file: ./logs/${spring.application.name}.log  
server:
  port: 9001
  context-path: /       
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
  healthcheck:
      enabled: true      