spring:
  application:
     name: eureka-server
server:
  port: 8001
  context-path: /
logging:  
  file: ./logs/${spring.application.name}.log  
eureka:
  instance:
    preferIpAddress: true 
    hostname: localhost
    statusPageUrl: https://${eureka.instance.hostname}/info
    healthCheckUrl: https://${eureka.instance.hostname}/health
    homePageUrl: https://${eureka.instance.hostname}/
  client:
    registerWithEureka: false  #声明不在Eureka服务注册自己
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck:
      enabled: true 