spring:
  application:
     name: client2-service
logging:  
  file: ./logs/${spring.application.name}.log  
server:
  port: 9002
  context-path: /      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/